local:
  embedding_model: "text-embedding-3-small"
  llm_model: "claude-3-5-sonnet-20240620"
  summary_llm_model: "claude-3-5-sonnet-20240620"
  vector_db_url: "redis://localhost:6379"
  vector_db_index_name: "idx:docs"
  vector_db_index_prefix: "docs:"
  vector_db_counter_name: "docs:counter"
