local:
  embedding_model: "text-embedding-3-small"
  llm_model: "claude-3-5-sonnet-20240620"
  summary_llm_model: "claude-3-5-sonnet-20240620"
  vector_db_url: "redis://localhost:6379"
  index_type: "json"
  index_name: "idx:docs"
  index_prefix: "doc:"
  counter_key: "docs:counter"