text:
  - name: $.text
    weight: 1.0
    no_stem: false
    sortable: false
    as_name: text
  - name: $.name
    weight: 1.0
    no_stem: false
    sortable: false
    as_name: name
  - name: $.dockey
    weight: 1.0
    no_stem: true
    as_name: dockey
  - name: $.doi
    weight: 1.0
    no_stem: true
    as_name: doi
  - name: $.citation
    weight: 1.0
    no_stem: true
    as_name: citation
  - name: $.journal
    weight: 1.0
    no_stem: true
    as_name: journal
  - name: $.volume
    weight: 1.0
    no_stem: true
    as_name: volume
  - name: $.issue
    weight: 1.0
    no_stem: true
    as_name: issue
  - name: $.authors
    weight: 1.0
    no_stem: true

numeric:
  - name: $.published_date
    sortable: true
    as_name: published_date
  - name: $.created_at
    sortable: true
    as_name: created_at

vector:
  - name: $.embedding
    algorithm: FLAT
    datatype: FLOAT32
    dims: 1536
    distance_metric: COSINE
    as_name: embedding

content_key: text
content_vector_key: embedding
