text:
  - name: text
    weight: 1.0
    no_stem: false
    sortable: false
  - name: title
    weight: 1.0
    no_stem: false
    sortable: false
  - name: dockey
    weight: 1.0
    no_stem: true
  - name: doi
    weight: 1.0
    no_stem: true
  - name: citation
    weight: 1.0
    no_stem: true
  - name: journal
    weight: 1.0
    no_stem: true
  - name: volume
    weight: 1.0
    no_stem: true
  - name: issue
    weight: 1.0
    no_stem: true
  - name: authors
    weight: 1.0
    no_stem: true

numeric:
  - name: published_date
    sortable: true
  - name: created_at
    sortable: true

vector:
  - name: embedding
    type: FLAT
    dims: 1536
    datatype: FLOAT32
    distance_metric: COSINE
    initial_cap: 1000

content_key: text
content_vector_key: embedding
